### ISSUE TITLE
Write the difference, advantage and disadvantage, among similar plugins

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/vim-findent#1]
https://github.com/kana/vim-obedient
https://github.com/ciaranm/detectindent
https://github.com/tpope/vim-sleuth

Any else?

**Comment by Shougo** [comment]
vim-findent

Pros:

Customization
Detection log

Cons:

Wrong indent detection problem https://github.com/lambdalisue/vim-findent/issues/2 -> Fixed from https://github.com/lambdalisue/vim-findent/commit/34df55c788396fb9e371fbf21b37259d4964f692
No softtabstop support -> Supported from https://github.com/lambdalisue/vim-findent/commit/34df55c788396fb9e371fbf21b37259d4964f692

**Comment by Shougo** [comment]
vim-sleuth

Pros:

Automatic
Improved ruby support

Cons:

Complex implementation
Hard to add filetype support

**Comment by Shougo** [comment]
detectindent

Pros:

Filetype comment support
tabstop and softtabstop support

Cons:

Complex
Manual detection
Hard to add filetype support

**Comment by lambdalisue** [comment]
Wow. Thanks a lot !

**Comment by lambdalisue** [comment]
Now the documentation is partially written in README and doc
